name: App Indespensa Workflow - Main

on:
  pull_request:
    branches: [ "main", "QA" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Give execution permissions to the gradlew file
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Output message for successful build
      - name: Check build success
        run: echo Build was successful!
