name: App Indespensa Workflow - Main

on:
  pull_request:
    branches: [ "main", "QA" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Output message for successful build
      - name: Check build success
        run: echo Build was successful!
